micronaut:
    application:
        name: crudDemo
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
    security:
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: R;%2kz]RXKh/>221$3dfg!@sfvvcA*&d5xXsdd!$3@
datasources:
    default:
        url: jdbc:postgresql://localhost:5432/crud-micronaut
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
        schema-generate: CREATE_DROP
        dialect: POSTGRES
jpa:
    default:
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: true
liquibase:
    datasources:
        default:
            change-log: 'classpath:db/liquibase-changelog.xml'